name: Cypress Tests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
        tags:
          description: 'Test scenario tags'  
  schedule:
    - cron: '0 1 * * *'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Tags: ${{ github.event.inputs.tags }}" 
  cypress-e2e-chrome78-ff70:
    name: Run on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:chrome