name: Cypress Tests

on: [push]

jobs:
  cypress-e2e-chrome78-ff70:
    name: Run on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:chrome