name: Cypress Tests
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs: 
  cypress-e2e-chrome78-ff70:
    name: Run on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:chrome